helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: false
  - name: image.tag
    value: 30-bbaae78404a1ee74d210be1ea775a7a9ebd13b1a
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: true
