helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: false
  - name: image.tag
    value: 3-61f700f4379838a71b1cea59f84b085d96bee0ed
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: true
