helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: false
  - name: image.tag
    value: 32-74838f41e6b206452907348fca7a2e911e50a144
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/devsecops/maven
    forcestring: true
