replicaCount: 1

image:
  repository: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/image-updator
  tag: v1
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
