apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-python-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: "{{ .Values.image.repository }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-my-python-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-my-python-app
    spec:
      containers:
        - name: my-python-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
