apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-python-app-service
spec:
  selector:
    app: {{ .Release.Name }}-my-python-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
